### ISSUE TITLE
Unable to run the test scrip

### ISSUE THREAD

**Issue by wilsonnkwan** [thinq-connect/pythinqconnect#4]
Hi, Thank you for your creation of this tool, however, when I run the test script to show devices, the following is shown:
Traceback (most recent call last):
  File "/home/john/thinqlist", line 11, in <module>
    asyncio.run(test_devices_list())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/john/thinqlist", line 9, in test_devices_list
    print("device_list : %s", response.body)
                              ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'body'

I am currently running on Ubuntu.

**Comment by wilsonnkwan** [comment]
I think I fixed it, I removed .body at the print and managed to get a one-liner list. 

But now that I have managed to get it to work to show the list, I don't know how to use your code to control my devices, you have any instruction on how to use your python tool?

**Comment by wilsonnkwan** [comment]
Nevermind, figured it out with ChatGPT. Example Script:
```
#!/usr/bin/python3

import asyncio
from aiohttp import ClientSession
from thinqconnect.thinq_api import ThinQApi, ThinQAPIException

async def control_device():
        async with ClientSession() as session:
                # Initialize API
                api = ThinQApi(
                        session=session,
                        access_token="thinqpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",  # Replace with your token
                        country_code="US",                # Replace with your country code
                        client_id="randomgeneratedID from README",       # Replace with your client ID
                )

                # Define the device ID and payload for the control
                device_id = "GET YOUR OWN DEVICE ID FROM THE TEST SCRIPT"  # Replace with your device's ID
                payload = {
                        "operation": {
                                "dehumidifierOperationMode": "POWER_ON"
                        }
                } #mine is a dehumidifier, go to LG's API site, only the ones that can rw can change.
                try:
                        # Send the control command
                        response = await api.async_post_device_control(
                                device_id=device_id,
                                payload=payload,
                        )
                        print("Control Response:", response)
                except ThinQAPIException as e:
                        print("Failed to control device:", e)
                except Exception as e:
                        print("An unexpected error occurred:", e)

# Run the asyncio event loop
asyncio.run(control_device())
```

Good Luck everyone.
